basicapp/urls.py
from django.conf.urls import url
from basicapp import views
from django.urls import path

urlpatterns = [
    #url(r'^$', views.first_app,name='first_app'),
    path('', views.index, name='index'),
    path('form/', views.form_name_view, name='form_name'),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from second_app import views
#from first_app import views

urlpatterns = [
    #path('', views.index, name='index'),
    #path('first_app/',include('first_app.urls')),

    path('second_app/',include('second_app.urls')),
#    path('',include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

second_app/urls.py
from django.conf.urls import url
from second_app import views
from django.urls import path
app_name = 'second_app'
urlpatterns = [
    #url(r'^$', views.first_app,name='first_app'),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),

    #path('login/', views.login, name='login'),
]

basicapp/models.py
from django.db import models

# Create your models here.

first_app/models.py
# Create your models here.
from django.db import models

class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()
    def __str__(self):
        return str(self.date)

class User(models.Model):
    first_name= models.CharField(max_length=264, unique=False)
    last_name= models.CharField(max_length=264, unique=False)
    email= models.EmailField(unique=True)
    def __str__(self):
        return str('{} {}'.format(self.first_name,self.last_name))

second_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.core import validators



class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError ("MAKE SURE EMAILS MATCH!")

second_app/forms.py
from django import forms
from django.contrib.auth.models import User
from second_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email', 'password')



class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basicapp/views.py
from django.shortcuts import render
from . import forms
# Create your views here.

def index(request):
    return render(request, 'basicapp/index.html')

def form_name_view(request):
    form =forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            #DO SOMETHING
            print(7859y7  )
    return render(request, 'basicapp/form.html',{'form':form})

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, AccessRecord

# Create your views here.

def index(request):
    webpages_list =  AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    return render(request,'first_app\index.html',context=date_dict)

second_app/views.py
from django.shortcuts import render
from second_app.forms import UserForm, UserProfileInfoForm
#from django.http import HttpResponse
#from second_app.models import User
#from second_app.forms import NewUserForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    #context_dict = {'text':'hello', 'number':1000 }
    return render(request, 'second_app/index.html')#,context_dict)

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'second_app/registration.html',
                                {'user_form': user_form,
                                'profile_form': profile_form,
                                'registered':registered})

def relative(request):
    return render(request, 'second_app/relative_url_template.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")


def user_login(request):
    if request.method == 'POST':
        username =request.POST.get('username')
        password =request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("login failed")
            print("Username:{}, pass: {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'second_app/login.html',{})

templates/basicapp/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Fill out the form</h1>
      </div>
    </div>

    <div class="container">
      <form method="POST">
              {{form.as_p}}
              {% csrf_token %}
            <input type="submit" name="btn btn-primary" value="Submit">
      </form>

    </div>
  </body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href={% static "css/mystyle.css" %}/>
  </head>
  <body>
    <h1>Hello this is index.html /Django Level Two</h1>
    <h2>Here are your access records:</h2>
      {{insert_me}}
      <div class="djangtwo">
      <img src={%static "images/download.jpg"%} alt="">
      {% if access_records %}
      <table>
          <thead>
            <th>Site Name</th>
            <th>Date Access Date</th>
          </thead>

        {% for acc in access_records %}
        <tr>
          <td>{{acc.name}}</td>
          <td>{{acc.date}}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
        <p>NO ACCESS RECORDS FOUND!</p>
      {% endif %}
      </div>
  </body>
</html>

templates/second_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class = "navbar brand" href="{% url 'second_app:index' %}">BRAND</a></li>
          <li><a class ="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class ="navbar-link" href="{% url 'second_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li><a class ="navbar-link" href="{% url 'logout' %}">logout</a></li>
          {% else %}
          <li><a class ="navbar-link" href="{% url 'second_app:user_login' %}">login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/second_app/index.html
<!DOCTYPE html>
{% extends "second_app/base.html" %}
    {%block body_block%}
<div class="jumbotron">
    <h1>WELCOME TO INDEX</h1>
</div>
    {% endblock %}

templates/second_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{%url 'basic_app:user_login'}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder='Enter Username'>

    <label for="password">Password</label>
    <input type="password" name="password">
  </form>

</div>

{% endblock %}

templates/second_app/other.html
<!DOCTYPE html>
{% extends "second_app/base.html" %}
    {%block body_block%}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of Template inheritance!</h2>
    {% endblock %}

templates/second_app/registration.html
<!DOCTYPE html>
{% extends "second_app/base.html" %}
{% load static %}
    {%block body_block%}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill our the form:</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="Register">

  </form>



  {% endif %}

</div>
    {% endblock %}

templates/second_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>relative</h1>
    <a href="{% url 'second_app:other' %}"> the other page</a>
    <a href="{% url 'admin:index' %}">admin</a>
  </body>
</html>